### ISSUE TITLE
Toughskin gland

### ISSUE THREAD

**Issue by Kaiser85** [Ludeon/RimWorld-it#118]
Ciao ho notato che la toughskin gland è stata tradotta come ghiandola di legno in tutte le linee, ma non centra nulla, possiamo metterla come dovrebbe essere in "ghiandola della pelle dura"?

**Comment by StoneNimRod** [comment]
Si infatti prima nella vecchia versione (1.1) era marcata come ghiandola di legno. Magari "ghiandola rinforzata" è meglio?

**Comment by Kaiser85** [comment]
Secondo me no, perché esiste anche la stoneskin gland  che è stata tradotta come ghiandola di pietra, quindi per differenziarle andrebbero messe come: "ghiandola della/per la pelle dura" e "ghiandola della/per la pelle di pietra".

**Comment by StoneNimRod** [comment]
Si hai ragione, facciamo "ghiandola della pelle rinforzata" e "ghiandola della pelle di pietra". Grazie per la notifica.
