### ISSUE TITLE
Berretto Vs Basco

### ISSUE THREAD

**Issue by Kaiser85** [Ludeon/RimWorld-it#122]
Ciao, prima che me lo dimentichi, ho notato che nel banco da sarto sia un normale berretto che il basco hanno lo stesso nome "berretto", io non riesco a capire dove si modifichi, riuscite a farlo voi?

**Comment by StoneNimRod** [comment]
Okey, ho trovato qualcosa nel file Royalty/DefInjected/ThingDef/Appareal_Royal.xml. Ho modificato il termine inglese "beret" in "basco" mentre "tuque" ho lascato "berretto".
