### ISSUE TITLE
Traduzione di Bestower

### ISSUE THREAD

**Issue by StoneNimRod** [Ludeon/RimWorld-it#133]
La traduzione dovrebbe essere: conferitore, dispensiere, elargitore.
Ma non mi garba molto...
Bestower sarebbe precisamente "colui che dona i titoli reali".
Inizialmente avevo utilizzato il termine "rappresentante reale".

Qualcuno ha un idea su come tradurlo bene? (In un modo non troppo lungo)

**Comment by Kaiser85** [comment]
Ciao

Secondo me sarebbe meglio usare sempre un termine chiaro nella nostra lingua piuttosto che tradurre letteralmente dall'inglese la singola parola, anche se un po più lungo.

Chi è il bestower in Rimworld? Colui che conferisce i titoli reali, rappresenta l'imperatore ed esegue la cerimonia. Per cui:

- Cerimoniere reale?
- Rappresentante reale?
- Conferitore reale dei titoli? 
- Sacerdote psichico? :D

Sarei più propenso per uno tra le prime due opzioni, meglio se cerimoniere reale.

**Comment by StoneNimRod** [comment]
Dai allora confermato per cerimoniere reale, anche se sacerdote psichico... XD

Grazie, procederò a modificare il termine.
