### ISSUE TITLE
Problema traduzione Ideology

### ISSUE THREAD

**Issue by AlessandroC91** [Ludeon/RimWorld-it#279]
Salve a tutti. Ho il seguente problema: Seguendo alla lettera le istruzioni per la traduzione, mi da la traduzione solo su Core ma non su Ideology. come posso risolvere?
Grazie per la vostra disponibilità e il vostro immenso lavoro.

Allego il report di traduzione:

[TranslationReport.txt](https://github.com/Ludeon/RimWorld-it/files/7331688/TranslationReport.txt)

**Comment by StoneNimRod** [comment]
Grazie per il report, infatti c'era un errore in un file della cartella Ideology. Ora dovrebbe funzionare.
