### ISSUE TITLE
Nuovo DLC

### ISSUE THREAD

**Issue by AndyDL24** [Ludeon/RimWorld-it#281]
Ciao a tutti sapete come aggiungere la lingua italiana per il nuovo DLC Biotech?

**Comment by Rexlord** [comment]
se e gia pronta dalle impostazioni del gioco

**Comment by AndyDL24** [comment]
Ho messo la lingua italiana nel gioco ma non mi mette la lingua italiana nel DLC

**Comment by AndyDL24** [comment]
[TranslationReport.txt](https://github.com/Ludeon/RimWorld-it/files/9858711/TranslationReport.txt)
Questo è il report della traduzione ma non si capisce molto

**Comment by StoneNimRod** [comment]
Ciao, purtroppo non è ancora stata aggiornata la traduzione di Biotech. Inizio a caricarla sul branch e vedere se riesco a mettere almeno le cose base. Buona giornata

**Comment by AndyDL24** [comment]
Ciao si se la carichi volendo posso dare una mano.

**Comment by StoneNimRod** [comment]
Ciao. Ho caricato i file di tutte le traduzioni. Adesso è solo da tradurre un po tutto. Per altre info puoi leggere [qui](https://github.com/Ludeon/RimWorld-it/issues/282).

**Comment by AndyDL24** [comment]
Si visto grazie mille ho iniziato a controllare Core mi sono fermato per il lavoro ma continuo appena posso.
