### ISSUE TITLE
Traduzione di Neologismi

### ISSUE THREAD

**Issue by Lunatico9** [Ludeon/RimWorld-it#34]
@lunargenta 
I neologismi tipo xericium e mechanoid vanno tradotti interpretando liberamente, non possono essere lasciati nella loro forma inglese.
Bisogna fare riferimento al fiction primer in italiano (https://docs.google.com/document/d/13aFF-7c1Ej_mzVEBjmHA-eKs2DFI8pbxczN2XoJ25LE/pub) per ciò che è lì.

**Comment by lunargenta** [comment]
Grazie del link non sapevo neanche esistesse.

Appena torno su github correggerò.
La mantide mh non so cosa sia perché non conosco i pokemon. Mh sta per?

--- Messaggio originale ---

Da: "Lunatico9" <notifications@github.com>
Inviata: 02 febbraio 2015 16:03
A: "Ludeon/RimWorld-it" <RimWorld-it@noreply.github.com>
Cc: "lunargenta" <assanta@hotmail.it>
Oggetto: [RimWorld-it] Traduzione di Neologismi (#34)

@lunargenta
I neologismi tipo xericium e mechanoid vanno tradotti interpretando liberamente, non possono essere lasciati nella loro forma inglese.
Bisogna fare riferimento al fiction primer in italiano (https://docs.google.com/document/d/13aFF-7c1Ej_mzVEBjmHA-eKs2DFI8pbxczN2XoJ25LE/pub) per ciò che è lì.

---
Reply to this email directly or view it on GitHub:
https://github.com/Ludeon/RimWorld-it/issues/34

**Comment by Lunatico9** [comment]
Beh l'ho tradotta ieri quindi è normale che non lo sapevi :) (quello italiano è l'unico fin ora :D)
mh era solo un'interiezione :PLo scyther nel gioco sembra una specie di mantide meccanica (nei pokemon anche è un qualcosa di simile) con le sue "protusioni" tipo coltello quindi penso possa andare bene così.Comunque ho ricontrollato tutte le modifiche che hai fatto nelle ultime settimane e corretto il possibile, c'è da rivedere il file Health_Diff_Injuries.xml perché se lo si prova nel gioco non va molto bene...
Chiederò a Tynan delucidazioni su come funziona il sistema.

Date: Mon, 2 Feb 2015 07:32:43 -0800
