### ISSUE TITLE
Info about Health_Diff_Injuries.xml

### ISSUE THREAD

**Issue by Lunatico9** [Ludeon/RimWorld-it#35]
@TynanSylvester This file defines different kinds of injuries (like, burns, cracks, cuts, and so on) but all of them seem to have the same "Treated" "InnerTreated" and "SolidTreated" fields, having the same string of text into it. I don't understand how one would suture a burn or set it, which seem to be actions dedicated respectively to cuts and bone fractures. We can't quite figure out how to translate these. Does the system automatically use the proper field based on the kind of injury that the body part sustained?

**Comment by TynanSylvester** [comment]
In a few cases the field won't ever be used. I recommend you either just
leave the nonsense fields untranslated or translate them exactly as they
are in English (if you really want).

**Comment by Lunatico9** [comment]
ok thanks
