### ISSUE TITLE
Avoid "pluralia majestatis"

### ISSUE THREAD

**Issue by stepps** [Ludeon/RimWorld-it#37]
In Italian there are 2 ways to refer to someone with formality and respect:

Lei. It is very similar to "Sie" in German and "Usted" in Spanish. It denotes a formal respect, sometimes hierarchical, but not necessarily so.

Voi. "pluralia majestatis", it uses a plural pronoun to refer to a singular person. This is archaic and was used only for people that represented a larger collective. It denotes a higher respect and submission (eg, king, pope and parents).

I would personally avoid both in an interface translation, where only the infinitive-impersonal form and the colloquial "tu", do not sound awkward

**Comment by Lunatico9** [comment]
Where does this create a problem?

**Comment by stepps** [comment]
Eg. "I vostri coloni" sounds awful and should be avoided. 
Plus there should be a general rule to go by, for consistency. It looks bad to have "dovrete fare" in one menu item, and "stai attento" in the next one.
