### ISSUE TITLE
Architect: Verb or Noun?

### ISSUE THREAD

**Issue by Lunatico9** [Ludeon/RimWorld-it#41]
Is the "Architect" in the menù supposed to be a verb (like, architect something) or a noun (like, the architect who builds something)?

**Comment by sammij** [comment]
I'd take it as a noun referring to the underlying category of possible actions, converting into "Architettura".
What also matters is how you'd translate the other tags at the same level, to keep consistency across.
My 2c.

**Comment by Lunatico9** [comment]
Thank you for the info. FYI, I'm getting back on the translation this month, I'm working on updating the older translation to the new alpha.

**Comment by Rexlord** [comment]
lunatico cerca su youtube rimworld traduzione
