### ISSUE TITLE
Conjugation Corrections

### ISSUE THREAD

**Issue by ChristianLJB** [Ludeon/RimWorld-it#73]
Alcune delle coniugazioni sono all'infinito quando non dovrebbero essere. 

Per esempio: <CloseButton>Chiudere</CloseButton> dovrebbe essere <CloseButton>Chiude</CloseButton> nel file "Dialogs_Various"

**Comment by menos-grande** [comment]
Li sto correggendo man mano che li incontro.

Per la precisione credo che si dovrebbero coniugare alla seconda persona imperativo, quindi 'chiudere' diventa 'chiudi', 'uscire' diventa 'esci', ecc... Per esempio i comandi principali nei sistemi operativi sono 'apri file', 'annulla', 'esci', tutti i comandi che dai a un programma sono alla seconda persona.
