### ISSUE TITLE
Missing Translations (Backstories)

### ISSUE THREAD

**Issue by ChristianLJB** [Ludeon/RimWorld-it#75]
Backstories are a huge issue with the Italian translation of Rimworld. Many of the backstories are not yet translated, and this needs to change. I've assigned myself to start, but I could use help if at all possible.

Backstories:
- [x] Athlete75
- [x] ArchotechSpy14
- [x] ApprenticeSmith9
- [x] AddictionCounsel61
- [x] AWOLSoldier26
- [x] Adventurer17
- [x] AdventurousYouth32
- [x] BattlefieldTech63
- [ ] BattleMechanic79
- [ ] BeastSlayer8
- [x] BehaviourResearch99
- [x] Blacksmith32
- [ ] BlacksmithShooter88
- [x] BlacksmithsSon72
- [ ] BloodgameSurvivor96
- [ ] BodyguardTrainee27
- [ ] BrothelGofer60
- [ ] Cadet99
- [ ] Caravaneer77
- [ ] CaravanTraveler5
- [ ] CaveChild67
- [ ] Chemist38
- [ ] ChiefEngineer74
- [ ] ChildKnave65
- [ ] ClanChief70
- [ ] ClassClown20
- [ ] CloneFarmed43
- [ ] CloneFarmer72
- [ ] CombatMedic16
- [ ] CorporateBuilder80
- [ ] CorpResearcher9
- [ ] CosmeticSurgeon52
- [ ] CraftShaper11
- [ ] CrimeBossChild12
- [ ] DataDecoder25
- [ ] DefenseLawyer2
- [ ] DestroyerGeneral40
- [ ] DischargedSoldier81
- [ ] Dreamer11
- [ ] DromedaryKnight31
- [ ] DrugLieutenant88
- [ ] DustyFarmHand63
- [ ] EnvoyOfTheStars91
- [ ] ExoticChef84
- [ ] FactoryWorker58
- [ ] FarmersSon51
- [ ] Flaneur73
- [ ] GalacticPage15
- [ ] GameFanatic49
- [ ] GangBoss0
- [ ] GangMember12
- [ ] HackerKid65
- [ ] HeadjackAddict49
- [ ] Healer46
- [ ] HexCellArtist19
- [ ] HiredGun99
- [ ] HumanTrafficker69
- [ ] Hunter7
- [ ] ImperialGeneral31
- [ ] JoywireAddict67
- [ ] KidScientist80
- [ ] Killer70
- [ ] LabGrownChild20
- [ ] LaborCampOrphan93
- [ ] LostMarine68
- [ ] MachineFixer97
- [ ] MadScientist65
- [ ] MadScientist79
- [ ] MarineCadet8
- [ ] MasterTrader3
- [ ] MechanicsEngineer7
- [ ] MechanoidHacker35
- [ ] MedievalThief74
- [ ] MentalPatient64
- [ ] MercenaryLeader48
- [ ] MercenaryRecruit61
- [ ] MilitantChild30
- [ ] MilitaryRecruit62
- [ ] Philosopher26
- [ ] PirateTrooper88
- [ ] PitGladiator18
- [ ] PlagueChild8
- [ ] PlagueDoctor99
- [ ] PlagueProdigy12
- [ ] PoliticalActivist61
- [ ] PoorKid76
- [ ] PrivateDetective57
- [ ] ProfessionalGamer86
- [ ] ProjectSubject48
- [ ] PyroAssistant17
- [ ] Ranger8
- [ ] RangerChild91
- [ ] RebelFighter79
- [ ] RebelStudent39
- [ ] RichBoy51
- [ ] Roboticist20
- [ ] SentimentalChild27
- [ ] SerialMurderer52
- [ ] ShipTechnician62
- [ ] Smuggler62
- [ ] SoleSurvivor99
- [ ] SpaceBartender52
- [ ] SpaceExplorer81
- [ ] SpaceMarine48
- [ ] SpaceMerchant61
- [ ] SpecialForces72
- [ ] SpeederRacer68
- [ ] SpoiledChild65
- [ ] StilettoAssassin10
- [ ] StreetPeddler62
- [ ] StreetUrchin39
- [ ] StreetUrchin51
- [ ] Student1
- [ ] SuperSoldier19
- [ ] SuperSoldier81
- [ ] TechnologyDoctor90
- [ ] TechScholar7
- [ ] ToasterRepairman81
- [ ] ToolMechanic40
- [ ] TraumatizedYouth62
- [ ] UprightDiplomat83
- [ ] UrbworldArmyBrat71
- [ ] UrbworldEnforcer55
- [ ] UrbworldUrchin13
- [ ] VideoGamer94
- [ ] VideoProducer97
- [ ] Warrior43
- [ ] WealthyStudent21
- [ ] WolfPackMember79
- [ ] YoungMaster70
- [ ] YouthSoldier75

I'm going to start by reorganizing, and then move on to actually doing translations. Again, anyone who wants to help is more than welcome!

Grazie,
O

**Comment by MaBo974** [comment]
Translated Blacksmith32

**Comment by MaBo974** [comment]
Translated BattlefieldTech63

**Comment by triccone** [comment]
salve il mio nome è triccone e mi piacerebbe sapere come funzionano un po' le cose prima di fare danni ho già fatto l'applicazione presso i ludeon studios forum e sono stato accettato quindi se mi spiegate a che punto siete e cosa state facendo adesso mi piacerebbe moltissimo aiutarvi

**Comment by MaBo974** [comment]
Ciao, in realtà io so poco più di te, nel senso che ho iniziato a tradurre qualcosa solo qualche giorno fa :-)
Quello che può darti più informazioni è @ChristianLJB 
Comunque se ti hanno autorizzato direttamente al master, ti basta fare la traduzione e poi la commit. Attenzione che ci sono alcune parole chiave che non vanno tradotte ma che sono dei segnaposti, ad esempio HE, HECAP, NAME, HIM, etc. ma l'ho scoperto analizzando i file, non so se esiste una guida.

**Comment by ChristianLJB** [comment]
@MaBo974 ,
@triccone ,

To start, I recommend downloading what's been done here. But first, you need to "purge" your local Italian translation folder, because there are a lot of files in there that aren't needed anymore. If you skip this step, you may end up with errors the rest of us aren't seeing.

To download...
1) Go to: https://github.com/Ludeon/RimWorld-it
2) Click "Clone or Download"
3) From the dropdown menu, select "Download ZIP"

Then, unzip the download and prepare to put it in your languages file. The download should be named something like "RimWorld-it-master". Select all of these folders/files:
- Backstories
- DefInjected
- Keyed
- Strings
- About
- FriendlyName
- LangIcon
- LanguageInfo
- Readme

Copy them, and then paste them into your empty ~/Languages/Italian folder

You should be good to go! You'll want to repeat this process from time to time, as more things get translated. If you notice something that's still not translated when you play the game, try to fix it on your own local files first. Once you've successfully done that, without producing any errors, you can come here and make the changes to the files on the git, and commit them to the main branch.

If you're having trouble finding something to fix, you can always come to the "Issues" tab and view an issue such as this. As you may have noticed, there are a lot of backstories which still need translating lol.

I hope this helps!

**Comment by MaBo974** [comment]
Translated BehaviourResearch99

**Comment by MaBo974** [comment]
Translated BlacksmithsSon72
