### ISSUE TITLE
(COMPLETARE) Backstories

### ISSUE THREAD

**Issue by Harkeidos** [Ludeon/RimWorld-it#87]
Traduzione completata.

**Comment by Chulics** [comment]
Come devo comportarmi per quanto riguarda gli accenti?

**Comment by Harkeidos** [comment]
Ciao, andrebbero cambiati tutti con le rispettive lettere accentate

**Comment by Chulics** [comment]
Grazie mille! Procedo con la pull request

**Comment by Harkeidos** [comment]
Traduzione completata.
