### ISSUE TITLE
(VERIFICA TRADUZIONE) DefInjected-->HairDef

### ISSUE THREAD

**Issue by Harkeidos** [Ludeon/RimWorld-it#88]
Il file contiene diverse traduzioni di acconciature per capelli.
Una prima traduzione è stata fatta, ma occorrerebbe verificare la correttezza di tutti i termini, specialmente per quelli dove non è stato trovato un corrispettivo in italiano.

**Comment by ChristianLJB** [comment]
Wavy → Ondulato?

Anche, "a ponta" è giusto?

**Comment by menos-grande** [comment]
> Wavy → Ondulato?
> 
> Anche, "a ponta" è giusto?

Wavy → Mossi se è riferito ai capelli.

"a ponta" non credo, non l'ho mai sentito?

**Comment by Harkeidos** [comment]
> > Wavy → Ondulato?
> > Anche, "a ponta" è giusto?
> 
> Wavy → Mossi se è riferito ai capelli.
> 
> "a ponta" non credo, non l'ho mai sentito?

Wavy è stato tradotto con mossi.

**Comment by Rexlord** [comment]
> > > Wavy → Ondulato?
> > > Anche, "a ponta" è giusto?
> > 
> > 
> > Wavy → Mossi se è riferito ai capelli.
> > "a ponta" non credo, non l'ho mai sentito?
> 
> Wavy è stato tradotto con mossi.

wavy hair  = capelli mossi poi ci sono capelli mossi corti o lunghi non penso sia specificato
