### ISSUE TITLE
(VERIFICA TRADUZIONE) DefInjected-->InteractionDef, RulePackDef, TaleDef

### ISSUE THREAD

**Issue by Harkeidos** [Ludeon/RimWorld-it#89]
Rivedere regole creazione frasi con la gestione automatica maschile/femminile e singolare/plurale

**Comment by Rexlord** [comment]
Harkeidos come ti contatto

**Comment by Panic04** [comment]
Puoi entrare nel gruppo discord se vuoi
(C'é anche Harkeidos)
Link: https://discord.gg/kKTHbaJ

**Comment by Harkeidos** [comment]
> Harkeidos come ti contatto

Puoi usare il link discord https://discord.gg/kKTHbaJ
oppure puoi scrivermi sul forum, se preferisci.

Ciao

**Comment by Harkeidos** [comment]
Traduzione completata
